Fixup: repo management not ignoring bill@

diff --git a/bin/clone b/bin/clone
--- a/bin/clone
+++ b/bin/clone
@@ -1,11 +1,11 @@
 #!/bin/bash
 
-
+ZGLUE_BILL_HOST=git@github.com/zglue-bill
+GIT_UNAME=bill
 GERRIT_HOST=101.132.142.37
 GERRIT_SSH_PORT=30149
 GERRIT_HTTP_PORT=14586
-ZGLUE_BILL_HOST=git@github.com/zglue-bill
-GIT_UNAME=bill
+GERRIT_HOST_URL="$GIT_UNAME@$GERRIT_HOST:$GERRIT_SSH_PORT"
 SDK_13="SDK_13.0.0-1"
 SDK_13_1="SDK_13.1.0"
 SDK_14="SDK_14.0.0"
@@ -21,24 +21,57 @@ RepoRename["nordic"]=SDK_13.0.0-1@3rd_Party_SDK
 RepoRename["sdk_13_1"]=SDK_13.1.0@3rd_Party_SDK
 RepoRename["sdk_14"]=SDK_14.0.0@3rd_Party_SDK
 
-# Repo2Host["mynewt-tools"]master@https://github.com/apache/mynewt-newt.git
-# Repo2Host["mynewt"]=master@https://github.com/apache/mynewt-core.git
-# https://github.com/koalaman/shellcheck.git
 Repo2Host["zephyr"]=master@github.com/zephyrproject-rtos/zephyr.git
 Repo2Host["RIOT"]=master@github.com/RIOT-OS
 Repo2Host["bknuttx"]=master@bitbucket.org/nuttx
-Repo2Host["sdk_13"]=$SDK_13@$GIT_UNAME@$GERRIT_HOST:$GERRIT_SSH_PORT
-Repo2Host["sdk_14"]=$SDK_14@$GIT_UNAME@$GERRIT_HOST:$GERRIT_SSH_PORT
-Repo2Host["nordic"]=$SDK_13_1@$GIT_UNAME@$GERRIT_HOST:$GERRIT_SSH_PORT
-Repo2Host["dialog"]=$DIALOG_SDK@$GIT_UNAME@$GERRIT_HOST:$GERRIT_SSH_PORT
-Repo2Host["nuttx"]=zdk@$GIT_UNAME@$GERRIT_HOST:$GERRIT_SSH_PORT
-Repo2Host["nuttx_apps"]=zdk@$GIT_UNAME@$GERRIT_HOST:$GERRIT_SSH_PORT
-Repo2Host["apps"]=zdk@$GIT_UNAME@$GERRIT_HOST:$GERRIT_SSH_PORT
-Repo2Host["auto_test"]=master@$GIT_UNAME@$GERRIT_HOST:$GERRIT_SSH_PORT
-Repo2Host["3rd_Party_SDK"]=master@$GIT_UNAME@$GERRIT_HOST:$GERRIT_SSH_PORT
 Repo2Host["fw_devtools"]=master@$ZGLUE_BILL_HOST
 Repo2Host["home-env"]=master@$ZGLUE_BILL_HOST
 
+# Repo2Host["mynewt-tools"]master@https://github.com/apache/mynewt-newt.git
+# Repo2Host["mynewt"]=master@https://github.com/apache/mynewt-core.git
+# https://github.com/koalaman/shellcheck.git
+
+function help()
+{
+        sed -n -e '/^#Help/,/^#Help/p' "$0" | grep ')'
+}
+
+#
+# Setup the repo table with a repo host url
+#
+function init_repo_table()
+{
+        local repo_host_url=
+
+        [ -z "$1" ] && return 1
+        repo_host_url="$1"; shift
+        [ -n "$DEBUG" ] && echo "repo_host_url ($repo_host_url)" >&2
+	Repo2Host["sdk_13"]=$SDK_13@$repo_host_url
+	Repo2Host["sdk_14"]=$SDK_14@$repo_host_url
+	Repo2Host["nordic"]=$SDK_13_1@$repo_host_url
+	Repo2Host["dialog"]=$DIALOG_SDK@$repo_host_url
+	Repo2Host["nuttx"]=zdk@$repo_host_url
+	Repo2Host["nuttx_apps"]=zdk@$repo_host_url
+	Repo2Host["apps"]=zdk@$repo_host_url
+	Repo2Host["auto_test"]=master@$repo_host_url
+	Repo2Host["3rd_Party_SDK"]=master@$repo_host_url
+}
+
+#
+#
+#
+dump_Repo2Host()
+{
+        if ! init_repo_table "$1"   ; then
+                echo "Failed to init repo table." >&2
+                exit 1
+        fi
+        for key in ${!Repo2Host[@]} ; do
+                echo "key: $key   ${Repo2Host[$key]}"
+        done
+}
+
+KEYS="sdk_13 sdk_14 nordic dialog nuttx nuttx_apps apps auto_test 3rd_Party_SDK"
 #
 # Given a keyword or hint from the user find the branch,
 # repo, and URI associated and clone.
@@ -69,5 +102,25 @@ function clone()
         $CMD
 }
 
-clone $1
+SRC_REPO_URL="$GERRIT_HOST_URL"
+#Help
+while [ $# -ne 0 ] ; do
+        case "$1" in
+        -p | --print) dump_Repo2Host "$SRC_REPO_URL" ; exit
+                ;;
+        -h | --help) help; exit
+                ;;
+        -R | --repo ) SRC_REPO_URL="$2"; shift
+                ;;
+        *) TARGET="$1";
+                ;;
+        esac
+        shift
+done
+#Help
+
+if init_repo_table $SRC_REPO_URL ; then
+        clone $TARGET
+fi
+
 
diff --git a/bin/file-style b/bin/file-style
--- a/bin/file-style
+++ b/bin/file-style
@@ -1,13 +1,14 @@
 #!/bin/bash
 
 ##### Script personality goes below
-ZGLUE_SCRIPTS_DIR=/usr/share/zglue/scripts
-LIB_SCRIPT=lib_body.sh
+ZGLUE_SCRIPTS_DIR=${ZGLUE_SCRIPTS_DIR:-/usr/share/zglue/scripts}
+LIB_SCRIPT=${LIB_SCRIPT:-lib_body.sh}
+ZGLUE_LIBSTYLE=${ZGLUE_LIBSTYLE:-$ZGLUE_SCRIPTS_DIR/$LIB_SCRIPT}
 if [ ! -f $ZGLUE_SCRIPTS_DIR/$LIB_SCRIPT ] ; then
         echo "$ZGLUE_SCRIPTS_DIR/$LIB_SCRIPT not found." >&2
         exit 1
 fi
-. $ZGLUE_SCRIPTS_DIR/$LIB_SCRIPT
+source $ZGLUE_LIBSTYLE
 
 #
 # Help nessage describing the command line options
@@ -101,7 +102,12 @@ FILTER_FUNCTIONS="filter_out_whitespace filter_if_0 filter_for_externs"
 export GIT_ADD=
 export FILES=
 REPO_HOST="101.132.142.37"
-ACTIVELY_MANAGED_REPOS="nuttx@$REPO_HOST nuttx_apps@$REPO_HOST auto_test@$REPO_HOST"
+ACTIVELY_MANAGED_REPOS=( nuttx@$REPO_HOST nuttx_apps@$REPO_HOST auto_test@$REPO_HOST 3rd_Party_SDK@$REPO_HOST )
+declare -A REPO_FILTERS
+REPO_FILTERS[nuttx@$REPO_HOST]="filter_if_0 filter_out_whitespace filter_for_externs"
+REPO_FILTERS[nuttx_apps@$REPO_HOST]="filter_if_0 filter_out_whitespace filter_for_externs"
+REPO_FILTERS[auto_test@$REPO_HOST]="filter_out_whitespace"
+REPO_FILTERS[3rd_Party_SDK@$REPO_HOST]="filter_out_whitespace"
 
 if [ "$(basename $0)" != "pre-commit" ] ; then
         set_env $@
@@ -115,13 +121,13 @@ fi
 # to discover any potential files for processing.
 #
 if ! REPOROOT=$(find_repo $FILES) ; then
-        echo_err "${RED}Error looking for a repo root directory.${RESET}"
+        echo_err "${REDYLW}Error looking for a repo root directory.${RESET}"
         exit 1
 fi
 #
 # Check whether this repo is to be styled.
 #
-if ! in_managed_repo $ACTIVELY_MANAGED_REPOS ; then
+if ! in_managed_repo "${ACTIVELY_MANAGED_REPOS[@]}" ; then
         echo_dbg ":This working tree is not from an actively managed repo."
         echo_dbg ":Do nothing."
         exit 0
@@ -134,7 +140,7 @@ echo_dbg ":This repo is actively managed."
 #
 # If there are no files to process there weren't any style errors!
 #
-[ -z "$FILES" ] && echo_dbg  ":${GREEN}\tNo files to process.${RESET}" && exit 0
+[ -z "$FILES" ] && echo_dbg  ":${GRNGRN}\tNo files to process.${RESET}" && exit 0
 
 #
 # Assume the first file is representative of the location of the repo
@@ -151,20 +157,20 @@ echo_dbg REPOROOT
 # If there are no SRCS to format then by default there are no style errors.
 #
 SRCS=$(filter_for_srcfiles $FILES)
-[ -z "$SRCS" ] && Echo  "${GREEN}\tNo files, no style errors.${RESET}" && exit 0
+[ -z "$SRCS" ] && Echo  "${GRNGRN}\tNo files, no style errors.${RESET}" && exit 0
 echo_dbg SRCS REPOROOT ORIGIN
 
 if ! filter_files "$REPOROOT" $SRCS ; then
-        [ -n "$DEBUG" ] && VERBOSE=--verbose
-        MAIN_PHRASE="${RED}\tNuttx style errors found,"
+        [ "$DEBUG" = "1" ] && VERBOSE=--verbose
+        MAIN_PHRASE="${REDYLW}\tNuttx style errors found,"
         PHRASEX="left unstaged."
         if [ -n "$GIT_ADD" ] ; then
                 git add $VERBOSE $SRCS
-                PHRASEX="${GREEN}corrected, and  staged.${RESET}"
+                PHRASEX="${GRNGRN}corrected, and  staged.${RESET}"
         fi
         echo_err "$MAIN_PHRASE $PHRASEX"
-        echo_err "${RED}\tSee style.errs in the root of this repo ($REPOROOT)."
+        echo_err "${REDYLW}\tSee style.errs in the root of this repo ($REPOROOT)."
         exit 2
 fi
-Echo  "${GREEN}\tNo style errors found.${RESET}"
+Echo  "${GRNGRN}\tNo style errors found.${RESET}"
 
