Redirect trap handler output to stderr
Change-Id: Ib9c8d8a8c4075b04be8386c5a4e2bca1da8c662e

diff --git a/bin/map-hash b/bin/map-hash
--- a/bin/map-hash
+++ b/bin/map-hash
@@ -10,7 +10,7 @@
 
 _exit_on_error() {
     if [[ $? -ne 0 ]]; then
-        echo -e "\n$(basename ${0}): Error: Couldn't find the file you were looking for"
+        echo -e "\n$(basename ${0}): Error: Couldn't find the file you were looking for" >&2
     fi
 }
 trap _exit_on_error EXIT
