Sync mkfast.sh/Makefile to latest fast_api repo
Change-Id: I8c0a37866b340f3ee7e94f0f5f0c66f66712f60c

diff --git a/bin/mkfast b/bin/mkfast
--- a/bin/mkfast
+++ b/bin/mkfast
@@ -17,12 +17,23 @@ echo_dbg()
         echo -e ":: $@" >&2
 }
 
+retrieve_configs()
+{
+        local Hash=
+
+        Hash="$1"
+        if ! git checkout "$Hash" build/configs >/dev/null 2>&1 ; then
+                echo "Could not checkout config directory." >&2
+                return 1
+        fi
+}
+
 #
 # Wrap make to generalize an interface that automatically captures the output
 #
 do_make()
 {
-        local Config=
+        local CommitHash=
         local Target=
         local Arch=
 
@@ -31,13 +42,13 @@ do_make()
                 return 1
         fi
 
-        Config="$1" ; shift
+        CommitHash="$1" ; shift
         Target="$1" ; shift
         Results="$1"   ; shift
 
-        cp "$TMPDIR/$Config" .config
+#       cp "$TMPDIR/$Config" .config
 #       make ${MAKE_OPTS} deliverables $Target | tee $Results | sed -e '/=/s/^.*=//'
-        make ${MAKE_OPTS} deliverables $Target | tee $Results
+        make ${MAKE_OPTS} $Target | tee $Results
 }
 
 #
@@ -119,12 +130,14 @@ print_array "${TARGETS[@]}"
 CLEAR=clean
 CLEAR=distclean
 CONFIG=.config
+COMMIT_HASH=056ac757144fc5d008c7141a50e31e1fcc9e8233
 
 eval rm -f "${TARFILE%_*}*"
     (
+        cd $ROOT && retrieve_configs "$CommitHash"
         cd "$ROOT/build/gcc" || exit 1
 
-        do_make config.zeus1.sim distclean /tmp/foo >/dev/null 2>&1
+        do_make "$COMMIT_HASH" distclean /tmp/foo >/dev/null 2>&1
         rm -f "$ROOT/test.zeus*.txt"
         for i in $(seq 0 1 3) ; do
                 echo_dbg "TARGETS[$i] :: ${TARGETS[$i]}"
@@ -168,7 +181,7 @@ eval rm -f "${TARFILE%_*}*"
     fi
 exit  0
 ## :: End of ascii shell code.
-00000000: 1f8b 0800 8c00 9a5a 0003 ed96 5f6f b230  .......Z...._o.0
+00000000: 1f8b 0800 ef08 cc5a 0003 ed96 5f6f b230  .......Z...._o.0
 00000010: 14c6 b9f6 5334 f1de d082 7ab1 ec82 4175  ....S4....z...Au
 00000020: 4d18 2502 fb77 d318 c70c 09d3 3703 2eb6  M.%..w......7...
 00000030: 4fbf 16dd 521c 1b5b dea8 797d cfef 42d2  O...R..[..y}..B.
