This is pre filter version: unset GIT_DIR

diff --git a/bin/pre-commit b/bin/pre-commit
--- a/bin/pre-commit
+++ b/bin/pre-commit
@@ -1,44 +1,28 @@
 #!/bin/bash
 
+export GIT_ADD=
+export FILES=
+RED='\033[1;31m'
+GREEN='\033[1;32m'
+YELLOW='\033[1;33m'
+BLUE='\033[1;34m'
+RESET='\033[0;39;49m'
+MANAGED_REPO_LIST="nuttx nuttx_apps"
+MANAGED_HOST_IP="101.132.142.37"
+
+# hooks have this var set and it interferes with
+# some commands (i.e. git rev-parse ...)
 #
-# Shortcut to send output to stderr by default.
-#
-echo_err()
-{
-        echo -e "$@" >&2
-}
+unset GIT_DIR
 
 #
-# Shortcut to send output to stderr by default.
-#
-echo_dbg()
-{
-        [ -z "$DEBUG" ] && return
-
-        #
-        # If the first arg has no dereferenced value it is probably a string.
-        #
-        [  "${1:0:1}" == ":" ] && shift  && echo_err "$@" && return
-
-        for i in $@ ; do
-                echo -n -e "    ::  $i\t\t" >&2
-                echo -e "(${!i})" >&2
-        done
-}
-
-echo_wbg()
-{
-        [ -n "$DEBUG" ] && echo_err "$@" && return
-}
-
-#
-# Create a tmp file to be used by a 'find' call to
-# operate on every file of *.[ch]. See filter_style()
+# Create a tmp file to be used by a 'find' call to operate on every
+# file of *.[ch]. See style_file() and style_dir().
 #
 setup_flip_hashmark()
 {
         if [ -z "$1" ] ; then
-                echo_err ": Is this a file? ($1)?"
+                echo "Is this a file? ($1)?" >&2
                 return -1
         fi
         cat >$1 <<"EOF"
@@ -69,18 +53,14 @@ EOF
 
 set_files()
 {
+        local Files=
         local AGAINST=
         local Action=
         local GIT_CMD=
 
-        #
-        # Default to working on staged files in the index.
-        #
         Action="diff --cached"
-        [ "$1" == "unstaged" ] && Action="diff"
         GIT_CMD="git \$Action --name-status --diff-filter=d \$AGAINST | \
                         awk '{print \$NF}'"
-
         #
         # See if there are any staged files to check:
         #
@@ -88,8 +68,7 @@ set_files()
         [ -n "$Files" ] && echo $Files && return 0
 
         #
-        # Finding a lack of files to process turn to the most recent
-        # commit and assume a commit --amend occurred.
+        # Pick out the files updated in this commit that are c source files.
         #
         AGAINST="HEAD^"
         Files="$(eval $GIT_CMD)"
@@ -103,116 +82,10 @@ set_files()
 #
 find_repo()
 {
-        local TDIR=
-        TDIR=$(dirname "$1")
-
-        CMD="TDIR=$(dirname \$TDIR)"
-        PRE="$(echo $TDIR | sed -e 's/^\/.*//')"
-        if [ "$PRE" != '/' ] ; then
-                TDIR="."
-                CMD='TDIR="../$TDIR"'
-                RECMD='$(cd $TDIR && pwd)'
-        fi
-
-        echo_dbg TDIR CMD
-        while [ ! -d $TDIR/.git ] && [ ! -d $TDIR/boot/grub ] ; do
-                eval $CMD
-                [ -n "$DEBUG" ] && sleep 1
-        done
-        [ -n "$RECMD" ] && eval TDIR=$RECMD
-        #
-        # Send the results back through stdout.
-        #
-        [ -d $TDIR/.git ] && echo $TDIR || return 1
-
-        return 0
+        echo $(cd $(dirname $1) && git rev-parse --show-toplevel)
 }
 
-#
-# Apply astyle to the list of files
-#
-filter_style()
-{
-        local Files=
-        local Results=
-
-        Results=$1; shift
-
-        Files=$@
-        #
-        # Look first in the local directory (ORIGIN) to see if
-        # astyle is local and executable.  If not then ask 'which'
-        # and if that fails then return error.  While 'which' will
-        # only report executable files it could report "" (nothing).
-        #
-        ASTYLE=${ORIGIN}astyle
-        [ ! -x "$ASTYLE" ] && ASTYLE=$(which astyle)
-        [ ! -x "$ASTYLE" ] && echo_err "Unable to find the astyle program" && return 1
-
-        ASTYLE_OPTS=astyle-nuttx
-        STYLE_OPTIONS=${ORIGIN}${ASTYLE_OPTS}
-        ZGLUE_OPTS_DIR=/usr/share/zglue/styles
-        [ ! -f $STYLE_OPTIONS ] && STYLE_OPTIONS=$ZGLUE_OPTS_DIR/${ASTYLE_OPTS}
-
-        [ -z "$DEBUG" ]  && QUIET='-q'
-        echo_dbg ASTYLE STYLE_OPTIONS
-
-        [ -f "$STYLE_OPTIONS" ] || echo_err "Missing [$STYLE_OPTIONS]" || return 1
-
-        #
-        # style check the files to commit, quietly unless DEBUG is set.
-        #
-        CMD="$ASTYLE --options=$STYLE_OPTIONS $QUIET $Files"
-        echo_dbg CMD
-        $CMD
-
-        CMD="$TMPFILE $Files"
-        $CMD
-        git diff $Files > $Results 2>&1
-
-        # Remove incidental files generated by astyle and this script.
-        #
-        find . -type f -name "*.orig" -exec rm {} \;
-}
-
-#
-# Look for any code bracketed by "#if 0...#endif" and flag it.
-# and remove it in case the --add flag was passed.
-#
-filter_if_0()
-{
-        local Results=
-        local Files=
-
-        Results=$1; shift
-        Files=$@
-
-        for i in $Files ; do
-                if grep "^[ 	]*#if[ 	]*0" $i >/dev/null  2>&1 ; then
-                        sed -i -e '/^[ 	]*#if[ 	]*0/iXXX Remove this if 0!!' $i
-                fi
-        done
-}
-
-#
-# Look for externs lurking in header files.
-#
-filter_externs()
-{
-        local Files=
-
-        Files=$@
-        for i in $Files ; do
-                [ -n "${i%%*.h}" ] && continue
-                grep "^extern.*;" $i >/dev/null 2>&1 && sed -i \
-                        -e '/^extern.*;/iXXX Remove this extern!' $i
-        done
-}
-
-#
-# Run all filters on the files finishing with the astyle formatting last.
-#
-filter_files()
+style_files()
 {
         local RepoRoot=
         local Files=
@@ -226,7 +99,6 @@ filter_files()
         local RV=
 
         RV=1
-        RESULTS=${ORIGIN}style.errs
 
         #
         # Make sure this script is running from the repo root.
@@ -234,8 +106,31 @@ filter_files()
         [ -d "$1"/.git ] || return 1
 
         RepoRoot=$1; shift
-        [ ! -f "$1" ] && echo_err "No files to style." && exit 1
+        [ ! -f "$1" ] && echo "No files to style." >&2 && exit 1
         Files=$@
+
+        ASTYLE=${ORIGIN}astyle
+        [ ! -x "$ASTYLE" ] && ASTYLE=$(which astyle)
+        [ ! -x "$ASTYLE" ] && echo "${RED}No $ASTYLE found.  Can't continue.${RESET}" >&2 && exit 2
+
+        ASTYLE_OPTS=astyle-nuttx
+        RESULTS=${ORIGIN}style.errs
+        STYLE_OPTIONS=${ORIGIN}${ASTYLE_OPTS}
+        ZGLUE_OPTS_DIR=/usr/share/zglue/styles
+        [ ! -f $STYLE_OPTIONS ] && STYLE_OPTIONS=$ZGLUE_OPTS_DIR/${ASTYLE_OPTS}
+        [ ! -f $STYLE_OPTIONS ] && echo -e "${RED}Missing $STYLE_OPTIONS. Can't continue.${RESET}" >&2 && exit 1
+
+        [ -z "$DEBUG" ]  && QUIET='-q'
+        [ -n "$DEBUG" ] && echo ":: ASTYLE:         [$ASTYLE]" >&2
+        [ -n "$DEBUG" ] && echo ":: STYLE_OPTIONS:  [$STYLE_OPTIONS]" >&2
+
+        #
+        # style check the files to commit, quietly unless DEBUG is set.
+        #
+        CMD="$ASTYLE --options=$STYLE_OPTIONS $QUIET $Files"
+        [ -n "$DEBUG" ] && echo ":: CMD: [$CMD]" >&2
+        cd $RepoRoot
+        $CMD
 
         #
         # Adjust the results to account for minor variations from astyle
@@ -244,21 +139,21 @@ filter_files()
         TMPFILE=$(mktemp -p /tmp .cleanup_astyle.XXX)
         setup_flip_hashmark $TMPFILE
 
-        cd $RepoRoot
-        filter_if_0 $RESULTS $Files
-        filter_externs $RESULTS $Files
+        CMD="$TMPFILE $Files"
+        $CMD
+
+        git diff $Files > $RESULTS 2>&1
+
+        # Remove incidental files generated by astyle and this script.
         #
-        # Run filter_style last as it will gather all of the diffs into one file.
-        #
-        filter_style $RESULTS $Files
-        grep "^XXX" $RESULTS && unset GIT_ADD
+        find . -type f -name "*.orig" -exec rm {} \;
         cd $ORIGIN
 
         rm $TMPFILE
         #
         # Set return value based on size of output file.
         #
-        [ ! -s $RESULTS ] && RV=0 && echo "Remove $RESULTS" && rm $RESULTS
+        [ ! -s $RESULTS ] && RV=0 && echo "Remove $RESULTS" >&2 && rm $RESULTS
 
         return $RV
 }
@@ -273,10 +168,8 @@ strip_files()
 
         for file in "$@" ; do
                 tmp=${file%%*.[ch]}
-                [ -n "$tmp" ] && continue
-                [ "${file:0:1}" != "/" ] && file=$REPOROOT/$file
-                echo -n "$file "
-                echo_dbg file
+                [ -z "$tmp" ] && echo -n "$file "
+                [ -n "$DEBUG" ] && [ -z "$tmp" ] && echo ":: $file" >&2
         done
 }
 
@@ -285,15 +178,9 @@ strip_files()
 #
 git_committed()
 {
-        local IFS=
-        local Filter1=
-        local Filter2=
-
-        [ "$1" == "unstaged" ] && IFS=" " && echo_dbg "Setting IFS to a space"
-        Filter1="'/^${IFS}[AMC]/p'"
-        Filter2="'/^${IFS}[R]/p'"
-        git status -uno --porcelain=v1 | eval sed -n -e $Filter1 -e $Filter2 | \
-                awk '{print $NF}'
+        git status --porcelain=v1 | sed -n -e '/^[AMC]/s/^.*  *//p' \
+                                           -e '/^[R]/s/^.*  *//p' | \
+                                                awk '{print $NF}'
 }
 
 #
@@ -303,28 +190,16 @@ help()
 {
         cat <<"EOF"
 
-        style-file: [-h] [--git] [--add] [--file|-f] [<file 1> <file2> ... ]
-                style_file examines the local environment for c source files to
-                apply formatting rules to.  For every file listed on the command
-                line style_file will format only the *.c *.h files and generate
-                a diff file, style.errs, where you are running the program from.
-
-                A list of files may also be provided as a file containing a list
-                of files.  Use the '-f <file name>' flag.
-
-                If no files are provided on the command line then style_file will
-                first examine the files staged.  If there are no files found then
-                style_file examines the set of files in the moxt recent commit
-                and format the source files in that check-in.
+        style_file: [-h] [--git] [--add] [--file|-f] [<file 1> <file2> ... ]
 
         -h           Display this message
 
-   -g|  --git        Look to the git index and recent commits for the
-                     set of files to check.
+        --git        Look to the git index and repo for the
+                     set of files to format
 
-   -a | --add        Run 'git add ' on the files formatted
+        --add        Run 'git add ' on the files formatted
 
-   -f | --file       Provide the list of files to format as a file
+        --file/-f    Provide the list of files to format as a file
                      conbtaining the set of files to format
 
         *            Files provided on the command line
@@ -333,9 +208,37 @@ help()
         mutually exclusive
 
 EOF
-#       -w           Target the files in the working directory not in the index. 
+}
+
 #
+# Make sure this is running within a repo that is actually managed.
+# Which means this should only be active in a nuttx repo.
 #
+is_active_repo()
+{
+        if ! git rev-parse >/dev/null 2>&1; then
+                [ -n "$DEBUG" ] && echo "This is not a git repo!" >&2
+                return 1
+        fi
+
+        RemoteName=$(git  remote show)
+        eval RemoteUrl=$(git remote get-url $RemoteName)
+        RepoName=${RemoteUrl##*/}
+        eval RepoHost=${RemoteUrl%%$RepoName}
+
+        if ! echo $RepoHost | grep $MANAGED_HOST_IP >/dev/null 2>&1; then
+                [ -n "$DEBUG" ] && echo "This host is not the managing host." >&2
+                return 1
+        fi
+
+        for Repo in $MANAGED_REPO_LIST ; do
+                if [ "${RepoName##$Repo}" != $RepoName ] ; then
+                        [ -n "$DEBUG" ] && echo "This Repo is managed!" >&2
+                        return 0
+                fi
+        done
+
+        return 1
 }
 
 #
@@ -347,88 +250,74 @@ set_env()
 {
         while [ $# -ne 0 ] ; do
                 case $1 in
+                --git|-g) FILES="$(git_committed)"
+                        [ -n "$DEBUG" ] && echo ":: FILES is ($FILES)" >&2
+                        break
+                        ;;
                 --add) GIT_ADD=yes;
-                        ;;
-                -f|--file) [ ! -f "$2" ] && echo_err "No file? [$2]" && exit 1
-                        [ -f "$2" ] && FILES=$(cat $2 | sed -e 's/^[ 	]*//') && shift
-                        echo_dbg ":" "From containing file, list of files is \n($FILES)"
-                        if [ -z "$FILES" ] ; then
-                                echo_err "Failed to read files from "$2""
-                                exit 1
-                        fi
-                        [ -n "$FILES" ] && echo_dbg ":" "Found files."
-                        ;;
-                -g|--git) FILES="$(git_committed)"
-                        [ -z "$FILES" ] && echo_err "No files found to process." ; exit 0
-                        echo_dbg FILES
                         ;;
                 -h) help; exit 0;
                         ;;
-                -w) FILES=$(git_committed unstaged);
-                        [ -z "$FILES" ] && echo_err "No files found to process." ; exit 0
-                        ALT=unstaged
+                -f|--file) [ ! -f "$2" ] && echo "No file? [$2]" >&2 && exit 1
+                        if ! FILES=$(cat "$2" | sed -e 's/^[ 	]*//') ;\
+                         then
+                                echo "Failed to read files from "$2""
+                                exit 1
+                        fi
                         ;;
-                *) if [ -f "$1" ] ; then
+                *) [ -z "$1" ] && echo "No arg specified." && exit 1;
+                   [ ! -f "$1" ] && echo "No such file: ($1)" && exit 1
                         FILES="$FILES $1"
-                   elif [ ! -f "$1" ]  ; then
-                        echo "No such file: ($1)" && exit 1
-                   elif [ "$FILE_ARGS" != "1" ] ; then
-                        echo_err "Unknown or unexpected arg ($1)."
-                        [ -f "$1" ] && \
-                                echo_err "The list of files requires a preceding '--'."
-                   fi
                         ;;
                 esac
                 shift
         done
 }
-
 ORIGIN=$(pwd)/
-export GIT_ADD=
-export FILES=
-RED='\033[1;31m'
-GREEN='\033[1;32m'
-YELLOW='\033[1;33m'
-BLUE='\033[1;34m'
-RESET='\033[39;49m'
-FUNC="echo_err \"--> ${FUNCNAME[0]}\""
-
+[ -n "$DEBUG" ] && echo "ORIGIN: ($ORIGIN)" >&2
 if [ "$(basename $0)" = "style_file" ] ; then
         set_env $@
-elif [ "$#" -ne 0 ] ; then
-        echo_err "Ignoring command line arguments"
+elif ! is_active_repo ; then
+        [ -n "$DEBUG" ] && echo "This repo does not enforce a style check." >&2
+        exit 0
+        if [ "$#" -ne 0 ] ; then
+                [ -n "$DEBUG" ] && echo "Ignoring command line arguments" >&2
+        fi
 fi
 
-[ -z "$FILES" ] && FILES=$(set_files $ALT)
-#
-# If there are no files to process there weren't any style errors!
-#
-[ -z "$FILES" ] && echo -e "${GREEN}\tFound no files to process.${RESET}" && exit 0
+[ -z "$FILES" ] && FILES=$(set_files)
+if [ -z "$FILES" ] ; then
+        [ -n "$DEBUG" ] && /bin/echo -e "${GREEN}\tFound no files to process.${RESET}" >&2
+        #
+        # If there are no files to process there weren't any style errors!
+        #
+        exit 0
+fi
 
-[ -n "$REPOROOT" ] && cd $REPOROOT && REPOROOT=$(pwd) && cd $(ORIGIN)
+[ -n "$DEBUG" -a -n "$FILES" ] && echo ":: FILES    [$FILES]" >&2
 #
-# Assume the first file is representative of the location of the repo
+# Assume the first file represents the location
+# of the repo for all files processed.
 #
 REPOROOT=$(find_repo $FILES)
+[ -z "$REPOROOT" ] && echo -e "${RED}No repo (.git) found!${RESET}" >&2 && exit 1
+SRCS=$(strip_files $FILES)
 
-#
+
 # If there are no SRCS to format then by default there are no style errors.
 #
-SRCS=$(strip_files $FILES)
-[ -z "$SRCS" ] && echo -e "${GREEN}\tNo files, no style errors.${RESET}" && exit 0
-echo_dbg SRCS REPOROOT ORIGIN
+[ -z "$SRCS" ] && /bin/echo -e "${GREEN}\tNo style errors found.${RESET}" >&2 && exit 0
+[ -n "$DEBUG" ] && echo ":: SRCS:  [$SRCS]" >&2
+[ -n "$DEBUG" ] && echo ":: REPOROOT is [$REPOROOT]" >&2
+[ -n "$DEBUG" ] && echo ":: ORIGIN is [$ORIGIN]" >&2
 
-if ! filter_files $REPOROOT $SRCS ; then
+if ! style_files $REPOROOT $SRCS ; then
         [ -n "$DEBUG" ] && VERBOSE=--verbose
-        MAIN_PHRASE="${RED}\tNuttx style errors found,"
-        PHRASEX="left unstaged."
-        if [ -n "$GIT_ADD" ] ; then
-                git add $VERBOSE $SRCS
-                PHRASEX="${GREEN}corrected, and  staged.${RESET}"
-        fi
-        echo_err "$MAIN_PHRASE $PHRASEX"
-        echo_err "${RED}\tSee style.errs in the root of this repo ($REPOROOT)."
+        [ -n "$GIT_ADD" ] && git add $VERBOSE $SRCS
+        /bin/echo -e "${RED}\tNuttx style errors: Please correct." >&2
+        /bin/echo -e "${RED}\tSee style.errs in the root of this repo." >&2
+        /bin/echo -e "${RESET}"
         exit 2
 fi
-echo -e "${GREEN}\tNo style errors found.${RESET}"
+/bin/echo -e "${GREEN}Success!  There are no style errors.${RESET}" >&2
 
