Fix style-file to work on non-repo files.
    style-file should be able to process files independently
    from the repo.

    Turn strip_srcs() back on in wsstrip and fix bugs.

diff --git a/bin/style-file b/bin/style-file
--- a/bin/style-file
+++ b/bin/style-file
@@ -117,6 +117,15 @@ set_files()
 #
 find_repo()
 {
+        cd $(dirname $1) && git rev-parse --show-toplevel 2>/dev/null
+}
+
+
+#
+# Given a file path find the repo covering that file.
+#
+Find_repo()
+{
         local TDIR=
         TDIR=$(dirname "$1")
 
@@ -182,11 +191,28 @@ filter_style()
 
         CMD="$TMPFILE $Files"
         $CMD
-        git diff $Files > $Results 2>&1
+
+        # Ignore error messages so they themselves don't cause a style failure.
+        git diff $Files > $Results 2>/dev/null
 
         # Remove incidental files generated by astyle and this script.
         #
         find . -type f -name "*.orig" -exec rm {} \;
+}
+
+filter_whitespace()
+{
+        local file=
+        local Results=
+
+        Results="$1"; shift
+        for file in "$@" ; do
+                if [ ${file%%.c} == $file -a ${file%%.h} == $file ] ; then
+                        echo_dbg "Skipping $file"
+                        continue
+                fi
+                sed -i -e 's/[ 	]\+$//' $file
+        done
 }
 
 #
@@ -214,7 +240,9 @@ filter_if_0()
 filter_externs()
 {
         local Files=
+        local Results=
 
+        Results=$1; shift
         Files=$@
         for i in $Files ; do
                 [ -n "${i%%*.h}" ] && continue
@@ -223,6 +251,7 @@ filter_externs()
         done
 }
 
+FILTER_FUNCTIONS="filter_whitespace filter_if_0 filter_externs"
 #
 # Run all filters on the files finishing with the astyle formatting last.
 #
@@ -245,7 +274,7 @@ filter_files()
         #
         # Make sure this script is running from the repo root.
         #
-        [ -d "$1"/.git ] || return 1
+        [ "$(basename $0)" = "pre-commit" ] && [ ! -d "$1"/.git ] && return 1
 
         RepoRoot=$1; shift
         [ ! -f "$1" ] && echo_err "No files to style." && exit 1
@@ -258,9 +287,14 @@ filter_files()
         TMPFILE=$(mktemp -p /tmp .cleanup_astyle.XXX)
         setup_flip_hashmark $TMPFILE
 
-        cd $RepoRoot
-        filter_if_0 $RESULTS $Files
-        filter_externs $RESULTS $Files
+        [ -n "$RepoRoot" ] && cd $RepoRoot
+        for Func in $FILTER_FUNCTIONS ; do
+                $Func $RESULTS $Files
+        done
+#       filter_whitespace $RESULTS $Files
+#       filter_if_0 $RESULTS $Files
+#       filter_externs $RESULTS $Files
+
         #
         # Run filter_style last as it will gather all of the diffs into one file.
         #
@@ -290,7 +324,7 @@ strip_files()
                 [ -n "$tmp" ] && continue
 #               [ "${file:0:1}" != "/" ] && file=$REPOROOT/$file
                 tmp="$(echo $file | sed -n -e '/^\//p')"
-                [ -n "$tmp" ] && file=$REPOROOT/$file
+                [ -n "$tmp" ] && file=${REPOROOT}$file
                 echo -n "$file "
                 echo_dbg file
         done
@@ -421,11 +455,15 @@ fi
 #
 [ -z "$FILES" ] && Echo  "${GREEN}\tFound no files to process.${RESET}" && exit 0
 
-[ -n "$REPOROOT" ] && cd $REPOROOT && REPOROOT=$(pwd) && cd $(ORIGIN)
 #
 # Assume the first file is representative of the location of the repo
 #
 REPOROOT=$(find_repo $FILES)
+if [ $? -ne 0 -a "$(basename $0)" = "pre-commit" ] ; then
+        echo_err "No repo found."
+        exit 1
+fi
+[ -n "$REPOROOT" ] && REPOROOT="$REPOROOT"/
 
 #
 # If there are no SRCS to format then by default there are no style errors.
@@ -434,7 +472,7 @@ SRCS=$(strip_files $FILES)
 [ -z "$SRCS" ] && Echo  "${GREEN}\tNo files, no style errors.${RESET}" && exit 0
 echo_dbg SRCS REPOROOT ORIGIN
 
-if ! filter_files $REPOROOT $SRCS ; then
+if ! filter_files "$REPOROOT" $SRCS ; then
         [ -n "$DEBUG" ] && VERBOSE=--verbose
         MAIN_PHRASE="${RED}\tNuttx style errors found,"
         PHRASEX="left unstaged."
