Add fast_api as a build.
Change-Id: I8b2b822df0b5e89dd4aa92cb51508bc795cfc22a

diff --git a/bin/zmake b/bin/zmake
--- a/bin/zmake
+++ b/bin/zmake
@@ -63,6 +63,13 @@ pseudo_targets["clean_cruft"]=1
 pseudo_targets["clean_env"]=1
 
 #
+# Create a mapping of commands to type of repo.
+#
+declare -A REPO_BUILD_CMDS
+REPO_BUILD_CMDS["fast_api"]="build_fastapi"
+REPO_BUILD_CMDS["nuttx"]="build_nuttx"
+
+#
 # Trap all exits.
 #
 on_exit()
@@ -191,6 +198,17 @@ print_colors()
         done
 }
 
+#
+# Find out what kind of source tree we're in. Builds are configured
+# one way for say, nuttx, and another for fast_api.
+#
+# Assumes already in the repo tree.
+#
+find_repo_type()
+{
+        git remote -v | grep fetch | sed -e 's/^.*\///' -e 's/ *(.*)//' -e 's/\.git//'
+}
+
 find_repo_root()
 {
         if ! git rev-parse >/dev/null 2>&1 ; then
@@ -200,7 +218,15 @@ find_repo_root()
         git rev-parse --show-toplevel
 }
 
-set_app_list()
+#
+# fixed list of targets deferential to the future.
+#
+set_fastapi_targets()
+{
+        echo "zeus1 clean sim zeus2 clean sim"
+}
+
+set_nuttx_app_list()
 {
         local Board_Cfg=
         local File_Key=
@@ -256,7 +282,7 @@ make_one_target()
         Verbose="$1" ; shift
 
         echo_dbg "Target is $Target"
-        CMD=( "make" "Q=@" "$NO_ERRORS" "distclean" "$Target" )
+        CMD=( "make" "Q=@" "$NO_ERRORS" "$Target" )
 
         [ "${1,,}" = "verb" ] && Verbose="" ; shift
         [ "${Incremental,,}" = "yes" ] && CMD[1]="Q="
@@ -266,9 +292,70 @@ make_one_target()
         echo_dbg "CMD[1] : ${CMD[1]}"
         echo_dbg "CMD[2] : ${CMD[2]}"
         echo_dbg "CMD[3] : ${CMD[3]}"
-        echo_dbg "CMD[4] : ${CMD[4]}"
 
         eval ${CMD[@]}
+}
+
+build_fastapi()
+{
+        declare -a Targets=
+        local OutFile=
+        local repo_type=
+        local Fails=
+
+        Fails=0
+        repo_type="fast_api"
+        Targets=( $(set_fastapi_targets) )
+        echo_err "Compiling for $repo_type"
+        echo_dbg "Targets are: ${Targets[*]}"
+
+        for target in ${Targets[@]} ; do
+            OutFile="${OUT}.${repo_type}.${target}"
+            echo_err -n "Building $target ... "
+            if ! make_one_target $target > $OutFile  2>&1 ; then
+                echo_err "Build failed: $target. Rebuilding with verbose flag" > $OutFile 2>&1 
+                make_one_target $target "yes" "verb" > $OutFile 2>&1
+                [ -z "$Q" ] && echo_err "Failed building $target.  See $OutFile"
+                tail -25 ${OutFile}
+                Fails=$(( Fails + 1 ))
+                continue
+            fi
+            echo_err "Succeeded."
+        done
+        [ "$Fails" -ne 0 ] && echo_drr "$Fails builds failed."
+
+
+        return $Fails
+}
+
+build_nuttx()
+{
+    [ "${#BOARDS[@]}" -eq 0 ] && [ -n "$BOARD" ] && BOARDS=( "$BOARD" )
+    [ "${#BOARDS[@]}" -eq 0 ] && echo "?????????????????????" >&2 && \
+                BOARDS=( $(select_board "${BOARDS_LIST[@]}") )
+
+    echo_err "Compiling for ${BOARDS[*]}"
+    for board in "${BOARDS[@]}" ; do
+        [ ${#TARGETS[@]} -eq 0 ] && TARGET_DIRS="$(set_nuttx_app_list $board $FILE_KEY)"
+        [ ! -d "configs/$board" ] && echo "Not found: $board" && continue
+        (
+            cd configs/$board >/dev/null
+            for build in distclean $TARGET_DIRS "${TARGETS[@]}" ; do
+                [ -z "${pseudo_targets[$build]}" ] && OUTOUT="${OUT}.${board}.${build}"
+                    echo_err -n "Building $board/$build: ... "
+                    if ! make_one_target $build > $OUTOUT  2>&1 ; then
+                            [ -z "$Q" ] && echo "Build failed see ${OUTOUT}." >&2 && continue
+                            echo_err "Failed.\n"
+                            echo_err "Running an incremental verbose build ::"
+                            make_one_target $build "yes" "verb" > $OUTOUT 2>&1
+                            tail -15 ${OUTOUT}
+                            Fails=$(( Fails + 1 ))
+                            continue
+                    fi
+                    echo_err "Succeeded."
+            done
+        )
+    done
 }
 
 #
@@ -388,14 +475,8 @@ fi
 
 OBJS_FILE=/tmp/objs.built
 rm -f $OBJS_FILE
-declare -a CMD_ADDED
-CMD_ADDED=( "ls" "../../arch/arm/src/*.o" ">>" "$OBJS_FILE" "2>&1" )
-CMD_ADDED=()
 Fails=0
 
-[ "${#BOARDS[@]}" -eq 0 ] && [ -n "$BOARD" ] && BOARDS=( "$BOARD" )
-[ "${#BOARDS[@]}" -eq 0 ] && echo "?????????????????????" >&2 && BOARDS=( $(select_board "${BOARDS_LIST[@]}") )
-# for target in $(set_app_list $BOARDS $FILE_KEY); do
 #         make_targets["$target"]=1
 # done
 # DEFAULT_APPS="${!make_targets[@]}"
@@ -406,29 +487,9 @@ Fails=0
 TARGET_DIRS=${TARGET_DIRS:-$DEFAULT_APPS}
 [ "${VERBOSE:0:1}" = "V" ] && print_keyval
 
-echo_err "Compiling for ${BOARDS[*]}"
-for board in "${BOARDS[@]}" ; do
-    [ ${#TARGETS[@]} -eq 0 ] && TARGET_DIRS="$(set_app_list $board $FILE_KEY)"
-    [ ! -d "configs/$board" ] && echo "Not found: $board" && continue
-    (
-        cd configs/$board >/dev/null
-        for build in $TARGET_DIRS "${TARGETS[@]}" ; do
-            [ -z "${pseudo_targets[$build]}" ] && OUTOUT="${OUT}.${board}.${build}"
-                echo_err -n "Building $board/$build: ... "
-                if ! make_one_target $build > $OUTOUT  2>&1 ; then
-                        [ -z "$Q" ] && echo "Build failed see ${OUTOUT}." >&2 && continue
-                        echo_err "Failed.\n"
-                        echo_err "Running an incremental verbose build ::"
-                        make_one_target $build "yes" "verb" > $OUTOUT 2>&1
-                        tail -15 ${OUTOUT}
-                        Fails=$(( Fails + 1 ))
-                        continue
-                fi
-                echo_err "Succeeded."
-
-#           [ -n "${CMD_ADDED[*]}" ] && echo "Tabulating objects"
-#           eval ${CMD_ADDED[@]}
-        done
-    )
-done
+#
+# Corner Case: empty value (no mapping set)
+# Corner Case: illegal command (nonsense text)
+#
+$(${REPO_BUILD_CMDS["$(find_repo_type)"]})
 
